<div id="Articles">
    <div>
        <form action="ajouter.php" method="post">
            <h1>Ajouter un article</h1>
            <div>
                <label for="nom">Nom:</label>
                <input type="text" name="nom" id="nom" required="required">
            </div>
            <div>
                <label for="stock">Stock:</label>
                <input type="number" name="stock" id="stock" required="required">
            </div>
            <div>
                <label for="prix">Prix:</label>
                <input type="number" name="prix" id="prix" required="required">
            </div>
            <div>
                <label for="code">Code:</label>
                <input type="text" name="code" id="code" required="required">
            </div>
            <div>
                <label for="liens">Liens images:</label>
                <input type="text" name="liens" id="liens" placeholder="Liens des images séparé pas des virgules" required="required">
            </div>
            <div>
                <label for="description">Description:</label>
                <textarea name="description" id="description" rows="50"></textarea>
            </div>
            <div>
                <input type="submit" value="Ajouter article" class="btn">
            </div>
        </form>
        <form action="modifier.php" method="post">
            <h1>Modifier un article</h1>
            <div>
                <label for="nom">Nom:</label>
                <input type="text" name="nom" id="nom" required="required">
            </div>
            <div>
                <label for="stock">Stock:</label>
                <input type="number" name="stock" id="stock" required="required">
            </div>
            <div>
                <label for="prix">Prix:</label>
                <input type="number" name="prix" id="prix" required="required">
            </div>
            <div>
                <label for="code">Code:</label>
                <input type="text" name="code" id="code" required="required">
            </div>
            <div>
                <label for="liens">Liens images:</label>
                <input type="text" name="liens" id="liens" placeholder="Liens des images séparé pas des virgules" required="required">
            </div>
            <div>
                <label for="description">Description:</label>
                <textarea name="description" id="description" rows="50"></textarea>
            </div>
            <div>
                <input type="submit" value="Ajouter article" class="btn">
            </div>
        </form>
    </div>
    <div>
        <form action="supprimer.php" method="post">
            <h1>Supprimer un article</h1>
            <div>
                <label for="code">Code:</label>
                <input type="text" name="code" id="code" required="required">
            </div>
            <div>
                <input type="submit" value="Ajouter article" class="btn">
            </div>
        </form>
    </div>
</div>