<div class="bg">
    <section class="bg1" aria-label="Photos">
        <div class="carousel">
            <!-- <button class="carousel-button prev" data-carousel-button="prev"><i class="fas fa-arrow-right"></i></button> -->
            <!-- <button class="carousel-button next" data-carousel-button="next"><i class="fas fa-arrow-left"></i></button> -->
            <ul data-slides>
                <li class="slide">
                    <img src="https://cdn.pixabay.com/photo/2015/04/19/08/32/rose-729509_960_720.jpg" alt="image1">
                </li>
                <!-- <li class="slide">
                    <img src="https://cdn.pixabay.com/photo/2017/01/18/17/14/girl-1990347_960_720.jpg" alt="image2">
                </li>
                <li class="slide">
                    <img src="https://cdn.pixabay.com/photo/2018/08/16/19/56/wedding-rings-3611277_960_720.jpg" alt="image3">
                </li> -->
            </ul>
        </div>
    </section>
    <section class="bg2">
        <div class="box1">
            <img src="/img/carousel/image2.png" alt="">
        </div>
        <div class="text1">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum ipsam eum commodi modi reprehenderit dolore quasi aspernatur, consectetur error eos vero eligendi similique minima, consequuntur fuga dolorem. Minima, ipsam.
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum ipsam eum commodi modi reprehenderit dolore quasi aspernatur, consectetur error eos vero eligendi similique minima, consequuntur fuga dolorem. Minima, ipsam.
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum ipsam eum commodi modi reprehenderit dolore quasi aspernatur, consectetur error eos vero eligendi similique minima, consequuntur fuga dolorem. Minima, ipsam.
            </p>
        </div>
    </section>