<?php if(isset($_SESSION['email'])){?>
<div id="forum">
    <form action="forum.php" method="post">
        <?php if(!isset($_SESSION['pseudo'])){?>
            <div>
                <label for="pseudo">Pseudo: </label>
                <input type="text" name="pseudo" id="pseudo" required="required">
            </div>
        <?php } ?>
        <div>
            <label for="comment">Commentaire: </label>
            <input type="text" name="comment" id="comment">
        </div>
        <div><input type="submit" value="Envoyer"></div>
    </form>
    <h1>Les commentaires des utilisateurs</h1>
    <div>
        <?php foreach($comments as $comment){ ?>        
            <fieldset class="field">
                <legend><?=$comment['pseudo']?></legend>
                <p><?=$comment['comment']?></p>
                <p><?=$comment['comment_set']?></p>
            </fieldset>
        <?php }; ?>            
    </div>
</div>
<?php } ?>