<div class="lookbook">
    <div class="box-look">
        <div class="look 1">
            <img src="img\1.jpg" />
            <img src="img\2.jpg" />
            <img src="img\3.jpg" />
            <img src="img\4.jpg" />
            <img src="img\5.jpg" />
        </div>
        <div class="look 2">
            <img src="img\6.jpg" />
            <img src="img\7.jpg" />
            <img src="img\8.jpg" />
            <img src="img\9.jpg" />
            <img src="img\10.jpg" />
        </div>
        <div class="look 3">
            <img src="img\11.jpg" />
            <img src="img\12.jpg" />
            <img src="img\13.jpg" />
            <img src="img\14.jpg" />
            <img src="img\15.jpg" />
        </div>
    </div>
</div>